export const LOGIN_DETAILS = 'LOGIN_DETAILS';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const ADD_LOCATION = 'ADD_LOCATION';
export const GET_USERS = 'GET_USERS';
export const GET_ASSETS = 'GET_ASSETS';
export const ADD_ASSET = 'ADD_ASSET';
export const GET_PARTS = 'GET_PARTS';
export const ADD_PART = 'ADD_PART';
export const GET_TEAMS = 'GET_TEAMS';
export const ADD_TEAM = 'ADD_TEAM';
export const GET_METERS = 'GET_METERS';
export const GET_METER_CHANGE_LOG = 'GET_METER_CHANGE_LOG';
export const GET_WORK_ORDERS = 'GET_WORK_ORDERS';
export const ADD_WORK_ORDER = 'ADD_WORK_ORDER';
export const DETAILS = 'DETAILS';
export const FILTER = 'FILTER';
export const UPDATE ='UPDATE';
export const WORK_ORDER_PARTS  = 'WORK_ORDER_PARTS';
export const RESET_RESPONSE = 'RESET_RESPONSE';
export const RESET = 'RESET'

